// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var flashInOut;
    $('body').append('\
    <div id="contextlyFlashesHolder"></div>\
    ');
    $('#contextlyFlashesHolder').prepend('\
     <div id="ContextlyLoadedFlash" class="hide alert alert-success" style="\
    z-index: 10000000;\
    position: fixed;\
    left: 41%;\
    top: 2%;\
    width: 200px;\
      ">\
      <a class="close" id= "closeMyFlash" href="#">×</a>\
      <p>Contextly Loaded into page. Press shift + H to begin.</p>\
    </div>\
    ');
    $('#contextlyFlashesHolder').prepend('\
     <div id="draggableFlash" class="hide alert alert-success" style="\
    z-index: 10000000;\
    position: fixed;\
    left: 41%;\
    top: 2%;\
    width: 200px;\
      ">\
      <a class="close" id= "closeMyFlash" href="#">×</a>\
      <p>Element made draggable</p>\
    </div>\
    ');
    $('#contextlyFlashesHolder').prepend('\
     <div id="changeFontFlash" class="hide alert alert-success" style="\
    z-index: 10000000;\
    position: fixed;\
    left: 41%;\
    top: 2%;\
    width: 200px;\
      ">\
      <a class="close" id= "closeMyFlash" href="#">×</a>\
      <p>Font changed</p>\
    </div>\
    ');
    $('#contextlyFlashesHolder').prepend('\
     <div id="wrapClassFlash" class="hide alert alert-success" style="\
    z-index: 10000000;\
    position: fixed;\
    left: 41%;\
    top: 2%;\
    width: 230px;\
      ">\
      <a class="close" id= "closeMyFlash" href="#">×</a>\
      <p>Element wrapped in specified div</p>\
    </div>\
    ');
    $('#contextlyFlashesHolder').prepend('\
     <div id="addToClassFlash" class="hide alert alert-success" style="\
    z-index: 10000000;\
    position: fixed;\
    left: 41%;\
    top: 2%;\
    width: 230px;\
      ">\
      <a class="close" id= "closeMyFlash" href="#">×</a>\
      <p>Element added to specified div</p>\
    </div>\
    ');
    $('#contextlyFlashesHolder').prepend('\
     <div id="changeTagNameFlash" class="hide alert alert-success" style="\
    z-index: 10000000;\
    position: fixed;\
    left: 41%;\
    top: 2%;\
    width: 200px;\
      ">\
      <a class="close" id= "closeMyFlash" href="#">×</a>\
      <p>Element\'s tagName changed</p>\
    </div>\
    ');
    $('#contextlyFlashesHolder').prepend('\
     <div id="modifyClassFlash" class="hide alert alert-success" style="\
    z-index: 10000000;\
    position: fixed;\
    left: 41%;\
    top: 2%;\
    width: 200px;\
      ">\
      <a class="close" id= "closeMyFlash" href="#">×</a>\
      <p>Class changed</p>\
    </div>\
    ');
    $('#contextlyFlashesHolder').prepend('\
     <div id="resizableFlash" class="hide alert alert-success" style="\
    z-index: 10000000;\
    position: fixed;\
    left: 41%;\
    top: 2%;\
    width: 200px;\
      ">\
      <a class="close" id= "closeMyFlash" href="#">×</a>\
      <p>Element made resizable</p>\
    </div>\
    ');
    $('#contextlyFlashesHolder').prepend('\
     <div id="revertFlash" class="hide alert alert-success" style="\
    z-index: 10000000;\
    position: fixed;\
    left: 41%;\
    top: 2%;\
    width: 200px;\
      ">\
      <a class="close" id= "closeMyFlash" href="#">×</a>\
      <p>Change reverted</p>\
    </div>\
    ');
    $('#contextlyFlashesHolder').prepend('\
     <div id="failRevertFlash" class="hide alert alert-error" style="\
    z-index: 10000000;\
    position: fixed;\
    left: 41%;\
    top: 2%;\
    width: 200px;\
      ">\
      <a class="close" id= "closeMyFlash" href="#">×</a>\
      <p>No changes to revert</p>\
    </div>\
    ');
    flashInOut = function(id, callback) {
      id = "#" + id;
      $(id).fadeIn(1500, function() {
        return $(this).fadeOut();
      });
      if (callback) {
        return callback();
      }
    };
    $("#quill").animate({
      "left": "-30px",
      "top": "-280px"
    }, 1500, "linear", function() {
      flashInOut("changeFontFlash");
      $('.jumbotron h3').css("font-size", "150px");
      return $('.jumbotron h3').css("font-family", "Open Sans");
    });
    $("#quill").animate({
      "left": "-27px",
      "top": "-232px"
    }, 1500, "linear", function() {
      flashInOut("resizableFlash", function() {
        $(".jumbotron").animate({
          "height": "312px"
        }, 1500, "linear");
        return $("#quill").animate({
          "top": "-20px"
        }, 1500, "linear");
      });
      return $("#quill").animate({
        "top": "-55px"
      }, 1500, "linear", function() {
        flashInOut("addToClassFlash");
        $('#addTarget').append('<p>Shift + A: Add the clicked element to a specified class.</p>');
        $('#addObject').css("opacity", "0");
        $('#quill').animate({
          "left": "75px",
          "top": "-70px"
        }, 1500, "linear", function() {});
        flashInOut("draggableFlash");
        return $('#myDrag').animate({
          "left": "0px"
        }, 1500, "linear", function() {
          return $('#ContextlyLoadedFlash').fadeIn();
        });
      });
    });
    return $(document).bind('keypress', function(e) {
      if (event.shiftKey && event.which === 72) {
        return $('#ContextlyLoadedFlash').fadeOut();
      }
    });
  });

}).call(this);
