// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var flashInOut;
    flashInOut = function(id, callback) {
      id = "#" + id;
      $(id).fadeIn(1500, function() {
        return $(this).fadeOut();
      });
      if (callback) {
        return callback();
      }
    };
    $("#quill").animate({
      "left": "1150%"
    }, 1500, "linear", function() {
      flashInOut("changeFontFlash");
      $('.jumbotron h3').css("font-size", "150px");
      return $('.jumbotron h3').css("font-family", "Open Sans");
    });
    $("#quill").animate({
      "top": "65px"
    }, 1500, "linear", function() {
      flashInOut("resizableFlash", function() {
        $(".jumbotron").animate({
          "height": "312px"
        }, 1500, "linear");
        return $("#quill").animate({
          "top": "275px"
        }, 1500, "linear");
      });
      return $("#quill").animate({
        "top": "245px"
      }, 1500, "linear", function() {
        flashInOut("addToClassFlash");
        $('#addTarget').append('<p>Shift + A: Add the clicked element to a specified class.</p>');
        $('#addObject').css("opacity", "0");
        return $('#quill').animate({
          "left": "-120px",
          "top": "325px"
        }, 1500, "linear", function() {
          flashInOut("draggableFlash");
          $('#myDrag').animate({
            "left": "0px"
          }, 1500, "linear");
          return $('#quill').animate({
            "left": "180px"
          }, 1500, "linear", function() {
            $('#quill').animate({
              "left": "1300%",
              "top": "230px"
            }, 1500, "linear", function() {});
            return $('#ContextlyLoadedFlash').fadeIn();
          });
        });
      });
    });
    return $(document).bind('keypress', function(e) {
      if (event.shiftKey && event.which === 72) {
        return $('#ContextlyLoadedFlash').fadeOut();
      }
    });
  });

}).call(this);
